name: CSN Semgrep Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14.x"

      - name: Install semgrep
        run: pip install semgrep

      - name: Run semgrep
        run: semgrep --config auto --error || true
